Algoritmo "parimpar"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : O objetivo do algoritmo é identivicar se um numero é par ou impar
// Autor(a)    : Caio Fabrício D. Almeida
// Data atual  : 06/04/2026
Var
n:inteiro

Inicio
Escreva ("Digite um numero inteiro:")
Leia (n)

Se (n MOD 2 = 0) entao
Escreva("O número iformado é par")
Senao
Escreva("O número informado é impar")
Fimse

Fimalgoritmo